apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.5
          env:
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aniscore-deployment
  labels:
    app: aniscore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aniscore
  template:
    metadata:
      labels:
        app: aniscore
    spec:
      containers:
        - name: aniscore
          image: aniscore
          env:
            - name: ANISCORE_ENV
              value: dev
            - name: DATABASE_URL
              value: "postgres://postgres:password@postgres-service:5432"
---
apiVersion: v1
kind: Service
metadata:
  name: aniscore-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5432
      targetPort: 5432
