import Head from "next/head";
import Link from "next/Link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>
        Go to: <Link href="/score">the score</Link>
      </p>
    </div>
  );
}
